language: python
python:
    - "2.7"
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=examples/Blink/Blink/Blink.ino
install:
    - pip install -U platformio
    - platformio lib -g install MsTimer2 TimerOne DueTimer
script:
    - platformio ci --lib="." --project-conf platformio.ini
