language: python
python:
    - "2.7"
sudo: required
dist: trusty
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=examples/Blink/Blink/
    - PLATFORMIO_CI_SRC=examples/Console/Console/
    - PLATFORMIO_CI_SRC=examples/MQTT/MQTT/
matrix:
    allow_failures:
        - env: PLATFORMIO_CI_SRC=examples/MQTT/MQTT/MQTT.ino
install:
    - pip install -U platformio
    - platformio lib -g install TimerOne DueTimer PubSubClient 872
    # Tmp fix for Microchip gcc-pic32
    - sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0
script:
    - if [[ "PLATFORMIO_CI_SRC" == "examples/Blink/Blink/" ]]; then platformio ci --lib="." --project-conf examples/Blink/platformio.ini; fi
    - if [[ "PLATFORMIO_CI_SRC" == "examples/Console/Console/" ]]; then platformio ci --lib="." --project-conf examples/Console/platformio.ini; fi
    - if [[ "PLATFORMIO_CI_SRC" == "examples/MQTT/MQTT/" ]]; then platformio ci --lib="." --project-conf examples/MQTT/platformio.ini; fi
